### PR TITLE
fix: registry normalization in config

### PR DESCRIPTION
**Pull request by Xynnn007**
This PR includes the following:
* Normalizing registry name `"registry-1.docker.io"`, `"dockerhub.io"` to `"index.docker.io"`
* `lint fixes using cargo fmt` and `cargo clippy`

### CODE REVIEW

**Comment by keirlawson** [comment]
I've just run a `cargo fmt` on main so that its easier to pick apart formatting changes from other ones, can you rebase?

**Comment by Xynnn007** [comment]
> I've just run a `cargo fmt` on main so that its easier to pick apart formatting changes from other ones, can you rebase?

Yes, rebased it!

**Comment by keirlawson** [comment]
Ok looks good, would you be up for adding some tests for the nomalization stuff so that its clear how its supposed to function?

**Comment by Xynnn007** [comment]
Hi, done with some unit tests. The basic idea is the docker generated `confign.json` will record images in `dockerhub` with prefix `https://index.docker.io/v1/`

**Review by keirlawson — APPROVED** [review]
Thanks for contributing!

**Comment by Xynnn007** [comment]
@keirlawson Hi, I wonder when the next version including this commit will be published? We hope to include the crate within `Cargo.toml` :-)

**Comment by keirlawson** [comment]
I've just published 1.1.0 including this change

**Pull request merged**
